'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, Boxes, Check, ChevronRight, CircleHelp, Clock3, Code2, FileCode2, GitBranch, LayoutDashboard, LoaderCircle, Search, ShieldCheck, Sparkles, Terminal, Zap } from 'lucide-react';

const platforms={gitlab:'GitLab CI',jenkins:'Jenkins',github:'GitHub Actions',azure:'Azure Pipelines',circleci:'CircleCI',other:'Custom'};
const providerFallback=[{id:'rules',name:'Built-in rules',configured:true,model:'Pattern-based · local'},{id:'cloud',name:'Cloud AI',configured:false,model:'Not configured'},{id:'ollama',name:'Local AI · Ollama',configured:false,model:'Not configured'}];
function Brand(){return <span className="brand-mark"><Activity size={23} strokeWidth={2.4}/></span>}

export default function Advisor(){
  const [runs,setRuns]=useState([]),[run,setRun]=useState(null),[selectedId,setSelectedId]=useState(''),[providers,setProviders]=useState(providerFallback),[provider,setProvider]=useState('rules');
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[tab,setTab]=useState('log'),[selectedLine,setSelectedLine]=useState(null);
  const activeProvider=providers.find(p=>p.id===provider);
  const lines=useMemo(()=>run?.logText.split('\n')||[],[run]);
  useEffect(()=>{(async()=>{try{const [runResponse,providerResponse]=await Promise.all([fetch('/api/runs?status=failed'),fetch('/api/providers')]);const runData=await runResponse.json(),providerData=await providerResponse.json();if(!runResponse.ok)throw new Error(runData.error);setRuns(runData.runs);if(providerResponse.ok)setProviders(providerData.providers);const requested=new URLSearchParams(window.location.search).get('run');const id=runData.runs.some(item=>item.id===requested)?requested:runData.runs[0]?.id;if(id)await selectRun(id);}catch(e){setError(e.message||'Could not load failures.');}finally{setLoading(false);}})();},[]);
  async function selectRun(id){setSelectedId(id);setResult(null);setSelectedLine(null);setError('');const response=await fetch(`/api/runs/${id}`);const data=await response.json();if(!response.ok)throw new Error(data.error);setRun(data.run);}
  async function analyze(){if(!run||busy)return;setBusy(true);setError('');setResult(null);try{const response=await fetch(`/api/runs/${run.id}/diagnose`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider})});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);}catch(e){setError(e.message||'The advisor could not complete this investigation.');}finally{setBusy(false);}}
  function evidence(line){setTab('log');setSelectedLine(line);setTimeout(()=>document.getElementById(`advisor-line-${line}`)?.scrollIntoView({behavior:'smooth',block:'center'}),0);}
  return <div className="app-shell management-shell">
    <aside className="sidebar"><a className="brand" href="/dashboard"><Brand/><span>Pipeline<span className="brand-light">Medic</span><small>DELIVERY CONTROL PLANE</small></span></a><div className="workspace-label"><span className="workspace-avatar">PM</span><span>Local workspace<small>Evidence advisor</small></span><span className="status-dot"/></div><div className="nav-caption">CONTROL PLANE</div><nav aria-label="Main navigation"><a className="nav-item" href="/dashboard"><LayoutDashboard size={18}/><span>Dashboard</span></a><a className="nav-item" href="/pipelines"><Boxes size={18}/><span>Pipelines</span></a><a className="nav-item active" href="/advisor"><Sparkles size={18}/><span>Advisor</span><span className="nav-active-dot"/></a><a className="nav-item" href="/doctor"><Activity size={18}/><span>Log sandbox</span></a></nav><div className="sidebar-bottom"><div className="privacy-card"><ShieldCheck size={21}/><strong>Evidence before advice.</strong><p>Every displayed citation must point to a real stored log line.</p></div><div className="sidebar-footer"><span className="version">v0.3 · ADVISOR</span></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><span>Control plane</span><ChevronRight size={14}/><strong>Advisor</strong></div><div className="topbar-right"><span className="local-label"><span className="status-dot"/> Advice only</span><span className="avatar">PM</span></div></header>
      <main className="advisor-main"><div className="page-heading"><div><div className="eyebrow"><span className="tiny-pulse"/> RUN-AWARE INVESTIGATION</div><h1>Start with the failed run, then follow the evidence.</h1><p>The advisor combines the stored job log, pipeline configuration and runtime context without executing repairs.</p></div></div>
        <div className="advisor-layout">
          <section className="panel advisor-inbox" aria-label="Failed runs"><div className="panel-heading"><div className="heading-with-icon"><AlertTriangle size={17}/><h2>Failure inbox</h2></div><span className="subtle-label">{runs.length} OPEN</span></div>{loading?<div className="advisor-loading"><LoaderCircle className="spin"/>Loading failures…</div>:<div className="advisor-run-list">{runs.map(item=><button key={item.id} className={selectedId===item.id?'selected':''} onClick={()=>selectRun(item.id)}><span className={`platform-icon ${item.platform}`}><GitBranch size={15}/></span><span><strong>{item.pipelineName}</strong><small>#{item.runNumber} · {item.branch}</small></span><ArrowRight size={13}/></button>)}</div>}</section>
          <section className="panel advisor-evidence" aria-label="Run evidence">{run?<><div className="advisor-run-heading"><div><span className="section-kicker">SELECTED FAILURE</span><h2>{run.pipelineName} <small>#{run.runNumber}</small></h2><p>{platforms[run.platform]} · {run.branch} · <code>{run.commitSha.slice(0,7)}</code></p></div><span className="synthetic-label">{run.synthetic?'SYNTHETIC DEMO':'INGESTED RUN'}</span></div><div className="advisor-context"><span><GitBranch size={12}/>{run.branch}</span><span><Clock3 size={12}/>{run.durationSeconds}s</span><span>{run.jobsFailed}/{run.jobsTotal} jobs failed</span><span>{run.runnerLocation}</span></div><div className="advisor-tabs" role="tablist"><button className={tab==='log'?'selected':''} onClick={()=>setTab('log')} role="tab" aria-selected={tab==='log'}><Terminal size={14}/>Job log</button><button className={tab==='config'?'selected':''} onClick={()=>setTab('config')} role="tab" aria-selected={tab==='config'}><FileCode2 size={14}/>Pipeline config</button></div><div className="advisor-code" aria-label={tab==='log'?'Job log':'Pipeline configuration'}>{tab==='log'?lines.map((line,index)=><div id={`advisor-line-${index+1}`} className={selectedLine===index+1?'selected-line':''} key={index}><span>{index+1}</span><code>{line||' '}</code></div>):<pre>{run.configText}</pre>}</div><div className="advisor-controls"><div><label htmlFor="advisor-provider"><Sparkles size={13}/>Investigate with</label><select id="advisor-provider" value={provider} onChange={e=>{setProvider(e.target.value);setResult(null);}}>{providers.map(item=><option value={item.id} key={item.id}>{item.name}{!item.configured?' · setup needed':''}</option>)}</select><small>{provider==='rules'?'Local patterns. No AI request.':activeProvider?.configured?activeProvider.model:'Configure this provider on the server.'}</small></div><button className="primary-button" onClick={analyze} disabled={busy}><>{busy?<LoaderCircle className="spin" size={16}/>:<Zap size={16}/>}</>{busy?'Investigating…':'Investigate run'}<ArrowRight size={15}/></button></div></>:<div className="workbench-empty"><Search size={30}/><h2>Select a failed run</h2></div>}</section>
          <section className="panel advisor-result" aria-label="Advisor result"><div className="panel-heading"><div className="heading-with-icon"><Sparkles size={17}/><h2>Advisor findings</h2></div><span className="subtle-label">{result?result.provider==='rules'?'RULES':'AI':busy?'WORKING':'READY'}</span></div>{busy?<div className="advisor-result-empty"><LoaderCircle className="spin" size={28}/><h3>Checking each claim against the log…</h3></div>:result?<div className="advisor-findings"><div className="advisor-summary"><span className={`certainty-badge ${result.certainty==='needs-context'?'uncertain':''}`}><span/>{result.certainty.replaceAll('-',' ')}</span><h3>{result.summary}</h3><p>{result.notice}</p></div>{result.causes.map((cause,index)=><article key={index}><span className="section-kicker">{index?'ADDITIONAL SIGNAL':'EVIDENCE-BACKED CAUSE'}</span><h4>{cause.title}</h4><p>{cause.explanation}</p>{cause.evidence.map(item=><button className="advisor-citation" key={item.line} onClick={()=>evidence(item.line)}><span>L{item.line}</span><code>{item.text}</code></button>)}</article>)}<div className="advisor-steps"><span className="section-kicker"><Code2 size={13}/>NEXT STEPS</span>{result.suggestedFixes.map((step,index)=><p key={index}><span>{index+1}</span>{step}</p>)}</div><div className="advisor-verify"><span className="section-kicker"><Check size={13}/>VERIFY</span>{result.verificationSteps.map((step,index)=><p key={index}><Check size={12}/>{step}</p>)}</div>{result.missingInformation.length>0&&<div className="advisor-missing"><CircleHelp size={14}/><div><strong>More context could help</strong>{result.missingInformation.map((item,index)=><p key={index}>{item}</p>)}</div></div>}</div>:<div className="advisor-result-empty"><ShieldCheck size={33}/><span>HUMAN-CONTROLLED ADVICE</span><h3>Ready when you are.</h3><p>Select a failed run and choose how the evidence should be analyzed.</p></div>}{error&&<div className="management-error inline-error" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}</section>
        </div><footer className="main-footer"><span><Brand/> Built for the people behind the pipelines.</span><span>No commands executed · evidence references validated</span></footer>
      </main>
    </div>
  </div>;
}
