'use client';

import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, ArrowRight, Boxes, CheckCircle2, ChevronRight, Clock3, GitBranch, LayoutDashboard, LoaderCircle, RefreshCw, Sparkles, Timer, TrendingUp } from 'lucide-react';

const platformNames={gitlab:'GitLab CI',jenkins:'Jenkins',github:'GitHub Actions',azure:'Azure Pipelines',circleci:'CircleCI',other:'Custom'};
const statusNames={success:'Passed',failed:'Failed',running:'Running',queued:'Queued',canceled:'Canceled'};
const duration=seconds=>seconds<60?`${seconds}s`:`${Math.floor(seconds/60)}m ${seconds%60}s`;
const age=value=>{const minutes=Math.max(1,Math.round((Date.now()-new Date(value))/60000));return minutes<60?`${minutes}m ago`:minutes<1440?`${Math.floor(minutes/60)}h ago`:`${Math.floor(minutes/1440)}d ago`;};

function Brand(){return <span className="brand-mark"><Activity size={23} strokeWidth={2.4}/></span>}
function Status({value,synthetic}){return <span className={`run-status ${value}`}><span/>{statusNames[value]}{synthetic&&<small>DEMO</small>}</span>}

export default function Dashboard(){
  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const response=await fetch('/api/dashboard');const body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);}catch(e){setError(e.message||'Could not load the dashboard.');}finally{setLoading(false);}}
  useEffect(()=>{load();},[]);
  const maxTrend=Math.max(1,...(data?.trend||[]).map(day=>day.total));
  return <div className="app-shell management-shell">
    <aside className="sidebar"><a className="brand" href="/dashboard"><Brand/><span>Pipeline<span className="brand-light">Medic</span><small>DELIVERY CONTROL PLANE</small></span></a><div className="workspace-label"><span className="workspace-avatar">PM</span><span>Local workspace<small>Operations overview</small></span><span className="status-dot"/></div><div className="nav-caption">CONTROL PLANE</div><nav aria-label="Main navigation"><a className="nav-item active" href="/dashboard"><LayoutDashboard size={18}/><span>Dashboard</span><span className="nav-active-dot"/></a><a className="nav-item" href="/pipelines"><Boxes size={18}/><span>Pipelines</span></a><a className="nav-item" href="/advisor"><Sparkles size={18}/><span>Advisor</span></a><a className="nav-item" href="/doctor"><Activity size={18}/><span>Log sandbox</span></a></nav><div className="sidebar-bottom"><div className="privacy-card"><TrendingUp size={21}/><strong>Operational context.</strong><p>Runs are normalized without replacing your CI provider.</p></div><div className="sidebar-footer"><span className="version">v0.3 · CONTROL PLANE</span></div></div></aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumbs"><span>Control plane</span><ChevronRight size={14}/><strong>Dashboard</strong></div><div className="topbar-right"><span className="local-label"><span className="status-dot"/> Normalized run data</span><button className="icon-button" onClick={load} aria-label="Refresh dashboard"><RefreshCw size={17} className={loading?'spin':''}/></button><span className="avatar">PM</span></div></header>
      <main className="dashboard-main"><div className="page-heading"><div><div className="eyebrow"><span className="tiny-pulse"/> OPERATIONS OVERVIEW</div><h1>Delivery health, without the tab switching.</h1><p>See the latest runs from every registered pipeline and move failed work into one investigation flow.</p></div><a className="primary-button" href="/advisor"><Sparkles size={16}/> Investigate failures</a></div>
        {data?.source.demo&&<div className="demo-banner"><AlertTriangle size={15}/><strong>Demo workspace</strong><span>{data.source.label}</span></div>}
        {loading&&!data?<div className="dashboard-loading"><LoaderCircle className="spin"/><span>Normalizing pipeline activity…</span></div>:error?<div className="management-error inline-error" role="alert">{error}<button onClick={load}>Retry</button></div>:data&&<>
          <section className="metric-grid" aria-label="Delivery metrics"><article><span>Enabled pipelines</span><strong>{data.summary.pipelines}</strong><small><Boxes size={13}/>Across three providers</small></article><article><span>Success rate</span><strong>{data.summary.successRate}%</strong><small><CheckCircle2 size={13}/>Completed demo runs</small></article><article className="metric-alert"><span>Open failures</span><strong>{data.summary.failed}</strong><small><AlertTriangle size={13}/>Ready to investigate</small></article><article><span>Average duration</span><strong>{duration(data.summary.averageDuration)}</strong><small><Timer size={13}/>Across completed runs</small></article></section>
          <div className="dashboard-grid">
            <section className="panel trend-panel"><div className="dashboard-section-heading"><div><span className="section-kicker">7-DAY ACTIVITY</span><h2>Pipeline outcomes</h2></div><span>{data.summary.runs} recent runs</span></div><div className="trend-chart" aria-label="Seven day run chart">{data.trend.map(day=><div className="trend-day" key={day.date}><div className="trend-bars"><i className="trend-success" style={{height:`${Math.max(3,day.success/maxTrend*100)}%`}}/><i className="trend-failed" style={{height:`${Math.max(3,day.failed/maxTrend*100)}%`}}/></div><span>{new Date(`${day.date}T00:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</span></div>)}</div><div className="chart-legend"><span><i className="success"/>Passed</span><span><i className="failed"/>Failed</span></div></section>
            <section className="panel patterns-panel"><div className="dashboard-section-heading"><div><span className="section-kicker">FAILURE SIGNALS</span><h2>Recurring categories</h2></div></div><div className="pattern-list">{data.failureGroups.length?data.failureGroups.map((group,index)=><div key={group.name}><span>{group.name}</span><div><i style={{width:`${Math.max(12,group.count/Math.max(...data.failureGroups.map(g=>g.count))*100)}%`}}/></div><strong>{group.count}</strong></div>):<p>No recurring categories yet.</p>}</div><p className="panel-note">Pattern groups come from stored log signals. The advisor performs evidence-linked analysis.</p></section>
          </div>
          <section className="panel failure-inbox"><div className="dashboard-section-heading"><div><span className="section-kicker">FAILURE INBOX</span><h2>Runs needing attention</h2></div><span>{data.failures.length} shown</span></div><div className="failure-list">{data.failures.map(run=><article key={run.id}><span className={`platform-icon ${run.platform}`}><GitBranch size={16}/></span><div><strong>{run.pipelineName} <small>#{run.runNumber}</small></strong><p>{platformNames[run.platform]} · {run.branch} · <code>{run.commitSha.slice(0,7)}</code></p></div><Status value={run.status} synthetic={run.synthetic}/><span className="run-age"><Clock3 size={12}/>{age(run.startedAt)}</span><a href={`/advisor?run=${encodeURIComponent(run.id)}`}>Investigate <ArrowRight size={14}/></a></article>)}</div></section>
          <section className="panel recent-runs"><div className="dashboard-section-heading"><div><span className="section-kicker">RECENT ACTIVITY</span><h2>All normalized runs</h2></div></div><div className="run-table"><div className="run-table-head"><span>Pipeline</span><span>Branch</span><span>Status</span><span>Duration</span><span>Started</span></div>{data.runs.map(run=><div className="run-table-row" key={run.id}><span><strong>{run.pipelineName}</strong><small>{platformNames[run.platform]} · #{run.runNumber}</small></span><code>{run.branch}</code><Status value={run.status} synthetic={run.synthetic}/><span>{duration(run.durationSeconds)}</span><span>{age(run.startedAt)}</span></div>)}</div></section>
        </>}
        <footer className="main-footer"><span><Brand/> Built for the people behind the pipelines.</span><span>Read-only operations view · provider execution stays external</span></footer>
      </main>
    </div>
  </div>;
}
